#!/usr/bin/env python3
"""Emit gpasm source for a build-time Morse callsign."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

DEFAULT_CALLSIGN = "N0PUF"
ORIGINAL_PADDING_WORDS = 117
MAX_CALLSIGN_LENGTH = len(DEFAULT_CALLSIGN) + ORIGINAL_PADDING_WORDS
_CALLSIGN_RE = re.compile(r"[A-Z0-9]+")


def normalize_callsign(value: str) -> str:
    callsign = value.strip().upper()
    if not callsign:
        raise ValueError("callsign must not be empty")
    if not _CALLSIGN_RE.fullmatch(callsign):
        raise ValueError("callsign must contain only ASCII letters A-Z and digits 0-9")
    if len(callsign) > MAX_CALLSIGN_LENGTH:
        raise ValueError(
            f"callsign is too long: {len(callsign)} characters; "
            f"maximum is {MAX_CALLSIGN_LENGTH}"
        )
    return callsign


def padding_words(callsign: str) -> int:
    return ORIGINAL_PADDING_WORDS + len(DEFAULT_CALLSIGN) - len(callsign)


def render(callsign_value: str) -> str:
    callsign = normalize_callsign(callsign_value)
    padding = padding_words(callsign)

    lines = [
        "; Generated by emit_callsign.py; do not edit.",
        f"; Build-time callsign: {callsign}",
        "",
        "send_callsign:",
        "        MOVLW     0x31 ; faster Morse timing",
        "        MOVWF     morse_unit_ticks",
        "        CALL      send_character_space",
    ]
    lines.extend(f"        CALL      send_morse_{character.lower()}" for character in callsign)
    lines.extend(
        [
            "        RETURN",
            "",
            "; Keep the page-3 computed tables anchored at program word 0x300.",
            "EMIT_CALLSIGN_PADDING MACRO",
        ]
    )
    lines.extend(
        "        DW        0x3FFF ; erased program-space padding"
        for _ in range(padding)
    )
    lines.extend(["        ENDM", ""])
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text() == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content)
    temporary.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--callsign", default=DEFAULT_CALLSIGN)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    try:
        content = render(args.callsign)
    except ValueError as error:
        parser.error(str(error))
    write_if_changed(args.output, content)


if __name__ == "__main__":
    main()
